name: Publish

on:
  push:
    branches: [ master ]

env:
  INPUT_TOKEN: ${{secrets.ASOFT_NPM_TOKEN}}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: viewmodel-core-npm-install
        run: npm install
        working-directory: ./viewmodel-core
      - name: remove none production assets
        run: rm src/test -rf
        working-directory: ./viewmodel-core
      - name: viewmodel-core-npm-run-build
        run: npm run build
        working-directory: ./viewmodel-core
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ASOFT_NPM_TOKEN }}
          package: ./viewmodel-core/package.json
          access: public
      
      - name: viewmodel-react-remove-viewmodel-core
        run: npm remove @asoft-ltd/viewmodel-core
        working-directory: ./viewmodel-react
      - name: viewmodel-react-add-viewmodel-core
        run: npm install @asoft-ltd/viewmodel-core@latest
        working-directory: ./viewmodel-react
      - name: viewmodel-react-npm-install
        run: npm install
        working-directory: ./viewmodel-react
      - name: viewmodel-react-npm-run-build
        run: npm run build
        working-directory: ./viewmodel-react
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ASOFT_NPM_TOKEN }}
          package: ./viewmodel-react/package.json
          access: public
        